### ISSUE TITLE
Changing References does nothing

### ISSUE THREAD

**Issue by ijoseph** [igvteam/igv.js-jupyter#11]
Greetings, thanks for a great piece of software. 

When I attempt to change the reference used (e.g., in order to use `hg38` rather than `hg19`) [according to the syntax specified in the example](https://github.com/igvteam/igv.js-jupyter/blob/master/examples/API%20Example.ipynb): `igv.Reference(fasta_url=...)`, nothing happens. I must use camelCase for my parameter names instead: `igv.Reference(fastaURL=...)`. 

I feel that is a bug because at the very least, there should be some sort of warning when my attempt to update the reference failed. Instead, it silently and dutifully serves me `hg19` coordinates. 

I think this is due to some issue with the [`to_camel_case` method](https://github.com/igvteam/igv.js-jupyter/blob/4b3877039c32216379f310c2dffc822996a1be77/igv/__init__.py#L30-L36) potentially not working.

**Comment by a-slide** [comment]
ref = Reference(id="GRCm38", fasta_url="./References/GRCm38_PRI_genome.fa.fai", index_url="./References/GRCm38_PRI_genome.fa.fai")

This worked for me, but it required a lot of tinkering around... 

Such a shame the package has not been documented and developed further, because the idea is awesome

**Comment by jrobinso** [comment]
Thanks @ijoseph .   The package hasn't been documented and developed because it didn't really catch on, and I'm a single person spread across several projects.     Of course, maybe it didn't catch on because its not documented well.  What features or additions beyond proper documentation do you think it needs to be a viable package?   I do not personally use Jupyter.

**Comment by a-slide** [comment]
Hi @jrobinso,
First, thanks a lot because I love the concept of having IGV running inside Jupyter. It is very handy to have a nice self-contained end to end analysis.   

I would say that one of the may drawback is that the interface is not very pythonic, which makes everything hard to use in jupyter. Since the function/class args are not explicitly declared in the signatures, the only way to find them is to read the raw code. I understood that it gives more flexibility, but declaring the args + having a docstring for each functions would actually make the package usable without having to guess the arguments values. I have a few other suggestions but I suppose it would be best to open an issue for each !

**Comment by jrobinso** [comment]
@a-slide Good point!  It's not pythonic because I'm not pythonic,  however, I am using python now for another project and I am getting better.   I would like to come back to this one and wrap it up well,  so please do open issues for your other suggestions.   It would be helpful.

**Comment by ijoseph** [comment]
Hm, yes, agreed with, @a-slide . It's almost there, just more documentation and error checking would make a huge positive difference, I think. 

But, this is my last day in the BioTech field (leaving my current company for a non-BioTech) one, so I suppose I have little horses in the race moving forward…

**Comment by jrobinso** [comment]
@a-slide I've started a major revision of this package.  The new interface is much simpler, particularly if you are familiar with igv.js.   Basically it mimics the igv.js API using python dictionaries where json-like config objects are specified in igv.js.   The dictionaries are converted to JSON and passed to the front end as messages.   I also added docstrings, but I'm not sure what you mean by "declaring the args".   Python is not my first or even second language,  but have a look and feedback is welcome.

I have not pushed this to pypi yet.
